### ISSUE TITLE
update for unreal engine 5

### ISSUE THREAD

**Issue by Andrey1994** [brainflow-dev/BrainFlowUnrealPlugin#8]

**Comment by neurogamedev** [comment]
👀

I'd like to use Muse 2 in Unreal Engine 5.2, so I'm awaiting with bated breath.

**Comment by Quicksymphony** [comment]
Same here for the neurosity headset. Unreal Engine has just recently mentioned 5.3 and the vs side will mandate vs2022 and up. So it would be nice to have a tutorial/update...5.2.1 is already having conflicts with some of the functionality.

**Comment by Andrey1994** [comment]
working on it but not an expert in unreal engine at all. If you solved it would be great if you share the fix
